title: Hacker-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "SomeHacker"
  email: "someone@somewebsite.somedomain"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
